In [1]:
import pandas as pd

# Pobranie danych

In [3]:
data = pd.read_csv('dane_projektowe_ny_collisions.csv', low_memory=False)

# Eksploracja danych wraz z określeniem dalszych kroków czyszczenia danych

In [4]:
data.describe()

,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,COLLISION_ID
count,1.415893e+06,1.415893e+06,1.612161e+06,1.612145e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06
mean,4.068864e+01,-7.386657e+01,2.631363e-01,1.185998e-03,5.060483e-02,6.302034e-04,2.098590e-02,9.242156e-05,1.916854e-01,4.633483e-04,2.765946e+06
std,1.200403e+00,2.438640e+00,6.584832e-01,3.644859e-02,2.316972e-01,2.577872e-02,1.445222e-01,9.677481e-03,6.206497e-01,2.334547e-02,1.506373e+06
min,0.000000e+00,-2.012371e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+01
25%,4.066882e+01,-7.397746e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.014464e+06
50%,4.072258e+01,-7.393002e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.422826e+06
75%,4.076789e+01,-7.386727e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.854210e+06
max,4.231832e+01,0.000000e+00,3.100000e+01,8.000000e+00,2.700000e+01,6.000000e+00,4.000000e+00,2.000000e+00,3.100000e+01,5.000000e+00,4.249104e+06

In [20]:
data.head(1000).loc[data['NUMBER OF PERSONS KILLED'] > 0]

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
7,2019-08-11T00:00:00.000,22:23,NaN,NaN,40.858210,-73.91679,"{'type': 'Point', 'coordinates': [-73.91679, 4...",MAJOR DEEGAN EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4187134,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
467,2019-08-02T00:00:00.000,10:25,QUEENS,11378,40.725918,-73.89535,"{'type': 'Point', 'coordinates': [-73.89535, 4...",GRAND AVENUE,69 STREET,NaN,...,NaN,NaN,NaN,NaN,4181646,Dump,NaN,NaN,NaN,NaN
540,2019-08-24T00:00:00.000,16:30,BROOKLYN,11236,40.644814,-73.90483,"{'type': 'Point', 'coordinates': [-73.90483, 4...",NaN,NaN,1037 EAST 95 STREET,...,Unspecified,NaN,NaN,NaN,4194033,Motorcycle,Pick-up Truck,NaN,NaN,NaN
708,2019-08-11T00:00:00.000,12:27,BROOKLYN,11230,40.619984,-73.96427,"{'type': 'Point', 'coordinates': [-73.96427, 4...",CONEY ISLAND AVENUE,AVENUE L,NaN,...,Unspecified,Unspecified,NaN,NaN,4188033,Sedan,Bike,Station Wagon/Sport Utility Vehicle,NaN,NaN
911,2019-08-29T00:00:00.000,2:35,NaN,NaN,40.834890,-73.86630,"{'type': 'Point', 'coordinates': [-73.8663, 40...",CROSS BRONX EXPY,NaN,NaN,...,NaN,NaN,NaN,NaN,4196472,Dump,NaN,NaN,NaN,NaN

Sprawdzenie czy kolumny liczbowe nie zawierają ujemnych wartości

In [15]:
list_of_numeric_columns=['NUMBER OF PERSONS INJURED', 'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED', 'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED', 'NUMBER OF MOTORIST KILLED' ]

In [17]:
for i in list_of_numeric_columns:
    min_value = data[i].min()
    if min_value < 0:
        print(f'kolumna {i} zawiera ujemne wartości, prawdopodobnie błędne dane')
    else:
        print(f'kolumna {i} zawiera zerowe lub dodatnie wartości')

kolumna NUMBER OF PERSONS INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PERSONS KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PEDESTRIANS INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PEDESTRIANS KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF CYCLIST INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF CYCLIST KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF MOTORIST INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF MOTORIST KILLED zawiera zerowe lub dodatnie wartości

Sprawdzenie czy suma kolumn o zabitych i rannych jest zgodna z kolumnami z sumami