In [75]:
import pandas as pd

# Pobranie danych

In [76]:
data = pd.read_csv('dane_projektowe_ny_collisions.csv', low_memory=False)

# Eksploracja danych wraz z określeniem dalszych kroków czyszczenia danych

In [77]:
data.describe()

,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,COLLISION_ID
count,1.415893e+06,1.415893e+06,1.612161e+06,1.612145e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06
mean,4.068864e+01,-7.386657e+01,2.631363e-01,1.185998e-03,5.060483e-02,6.302034e-04,2.098590e-02,9.242156e-05,1.916854e-01,4.633483e-04,2.765946e+06
std,1.200403e+00,2.438640e+00,6.584832e-01,3.644859e-02,2.316972e-01,2.577872e-02,1.445222e-01,9.677481e-03,6.206497e-01,2.334547e-02,1.506373e+06
min,0.000000e+00,-2.012371e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+01
25%,4.066882e+01,-7.397746e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.014464e+06
50%,4.072258e+01,-7.393002e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.422826e+06
75%,4.076789e+01,-7.386727e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.854210e+06
max,4.231832e+01,0.000000e+00,3.100000e+01,8.000000e+00,2.700000e+01,6.000000e+00,4.000000e+00,2.000000e+00,3.100000e+01,5.000000e+00,4.249104e+06

In [78]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1612178 entries, 0 to 1612177
Data columns (total 29 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   ACCIDENT DATE                  1612178 non-null  str
 1   ACCIDENT TIME                  1612178 non-null  str
 2   BOROUGH                        1127553 non-null  str
 3   ZIP CODE                       1127376 non-null  str
 4   LATITUDE                       1415893 non-null  float64
 5   LONGITUDE                      1415893 non-null  float64
 6   LOCATION                       1415893 non-null  str
 7   ON STREET NAME                 1298002 non-null  str
 8   CROSS STREET NAME              1079193 non-null  str
 9   OFF STREET NAME                219732 non-null   str
 10  NUMBER OF PERSONS INJURED      1612161 non-null  float64
 11  NUMBER OF PERSONS KILLED       1612145 non-null  float64
 12  NUMBER OF PEDESTRIANS INJURED  1612178 non-null  int64
 13  NUMBER OF PEDESTRIANS KILLED   1612178 non-null  int64
 14  NUMBER OF CYCLIST INJURED      1612178 non-null  int64
 15  NUMBER OF CYCLIST KILLED       1612178 non-null  int64
 16  NUMBER OF MOTORIST INJURED     1612178 non-null  int64
 17  NUMBER OF MOTORIST KILLED      1612178 non-null  int64
 18  CONTRIBUTING FACTOR VEHICLE 1  1607854 non-null  str
 19  CONTRIBUTING FACTOR VEHICLE 2  1396127 non-null  str
 20  CONTRIBUTING FACTOR VEHICLE 3  104254 non-null   str
 21  CONTRIBUTING FACTOR VEHICLE 4  21789 non-null    str
 22  CONTRIBUTING FACTOR VEHICLE 5  5622 non-null     str
 23  COLLISION_ID                   1612178 non-null  int64
 24  VEHICLE TYPE CODE 1            1606597 non-null  str
 25  VEHICLE TYPE CODE 2            1346858 non-null  str
 26  VEHICLE TYPE CODE 3            128742 non-null   str
 27  VEHICLE TYPE CODE 4            46009 non-null    str
 28  VEHICLE TYPE CODE 5            10150 non-null    str
dtypes: float64(4), int64(7), str(18)
memory usage: 667.6 MB

In [79]:
data.head(1000).loc[data['NUMBER OF PERSONS KILLED'] > 0]

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
7,2019-08-11T00:00:00.000,22:23,NaN,NaN,40.858210,-73.91679,"{'type': 'Point', 'coordinates': [-73.91679, 4...",MAJOR DEEGAN EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4187134,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
467,2019-08-02T00:00:00.000,10:25,QUEENS,11378,40.725918,-73.89535,"{'type': 'Point', 'coordinates': [-73.89535, 4...",GRAND AVENUE,69 STREET,NaN,...,NaN,NaN,NaN,NaN,4181646,Dump,NaN,NaN,NaN,NaN
540,2019-08-24T00:00:00.000,16:30,BROOKLYN,11236,40.644814,-73.90483,"{'type': 'Point', 'coordinates': [-73.90483, 4...",NaN,NaN,1037 EAST 95 STREET,...,Unspecified,NaN,NaN,NaN,4194033,Motorcycle,Pick-up Truck,NaN,NaN,NaN
708,2019-08-11T00:00:00.000,12:27,BROOKLYN,11230,40.619984,-73.96427,"{'type': 'Point', 'coordinates': [-73.96427, 4...",CONEY ISLAND AVENUE,AVENUE L,NaN,...,Unspecified,Unspecified,NaN,NaN,4188033,Sedan,Bike,Station Wagon/Sport Utility Vehicle,NaN,NaN
911,2019-08-29T00:00:00.000,2:35,NaN,NaN,40.834890,-73.86630,"{'type': 'Point', 'coordinates': [-73.8663, 40...",CROSS BRONX EXPY,NaN,NaN,...,NaN,NaN,NaN,NaN,4196472,Dump,NaN,NaN,NaN,NaN

Sprawdzenie czy kolumny liczbowe o zabitych i rannych nie zawierają ujemnych wartości

In [80]:
list_of_numeric_columns_injured_or_killed=['NUMBER OF PERSONS INJURED', 'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED', 'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED', 'NUMBER OF MOTORIST KILLED']

In [81]:
for i in list_of_numeric_columns_injured_or_killed:
    min_value = data[i].min()
    if min_value < 0:
        print(f'kolumna {i} zawiera ujemne wartości, prawdopodobnie błędne dane')
    else:
        print(f'kolumna {i} zawiera zerowe lub dodatnie wartości')

kolumna NUMBER OF PERSONS INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PERSONS KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PEDESTRIANS INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PEDESTRIANS KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF CYCLIST INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF CYCLIST KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF MOTORIST INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF MOTORIST KILLED zawiera zerowe lub dodatnie wartości

Sprawdzenie czy suma kolumn o zabitych i rannych jest zgodna z kolumnami z sumami

In [82]:
dict_killed_injured = {'NUMBER OF PERSONS INJURED': [['NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF CYCLIST INJURED', 'NUMBER OF MOTORIST INJURED' ], 'CHECK_INJURED'], 'NUMBER OF PERSONS KILLED': [['NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST KILLED'], 'CHECK_KILLED']}
data[['CHECK_KILLED', 'CHECK_INJURED']] = 0
for i, j in dict_killed_injured.items():
    for k in j[0]:
        data[j[1]] = data[j[1]] + data[k]
data

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5,CHECK_KILLED,CHECK_INJURED
0,2019-08-05T00:00:00.000,16:30,QUEENS,11434,40.676052,-73.790184,"{'type': 'Point', 'coordinates': [-73.790184, ...",NaN,NaN,150-08 123 AVENUE,...,NaN,NaN,4184637,Sedan,Pick-up Truck,NaN,NaN,NaN,0,0
1,2019-08-27T00:00:00.000,16:02,BROOKLYN,11225,40.657780,-73.951096,"{'type': 'Point', 'coordinates': [-73.951096, ...",NaN,NaN,288 HAWTHORNE STREET,...,NaN,NaN,4195773,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,0,0
2,2019-08-15T00:00:00.000,17:57,MANHATTAN,10002,40.718143,-73.993835,"{'type': 'Point', 'coordinates': [-73.993835, ...",CHRYSTIE STREET,GRAND STREET,NaN,...,NaN,NaN,4202457,Sedan,NaN,NaN,NaN,NaN,0,1
3,2019-08-30T00:00:00.000,21:53,BRONX,10460,40.840534,-73.866610,"{'type': 'Point', 'coordinates': [-73.86661, 4...",NaN,NaN,1837 EAST TREMONT AVENUE,...,NaN,NaN,4198749,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,0,0
4,2019-08-06T00:00:00.000,9:45,MANHATTAN,10016,40.745440,-73.975400,"{'type': 'Point', 'coordinates': [-73.9754, 40...",EAST 35 STREET,2 AVENUE,NaN,...,NaN,NaN,4183798,Station Wagon/Sport Utility Vehicle,Bike,NaN,NaN,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612173,2012-07-21T00:00:00.000,22:46,BROOKLYN,11226,40.651741,-73.965241,"{'type': 'Point', 'coordinates': [-73.9652409,...",PARADE PLACE,CROOKE AVENUE,NaN,...,NaN,NaN,147595,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN,0,0
1612174,2012-07-09T00:00:00.000,16:45,NaN,NaN,NaN,NaN,NaN,EDWARD L GRANT HIGHWAY,WEST 169 STREET,NaN,...,NaN,NaN,85220,PASSENGER VEHICLE,LIVERY VEHICLE,PASSENGER VEHICLE,NaN,NaN,0,5
1612175,2012-07-09T00:00:00.000,14:35,NaN,NaN,40.791492,-73.935763,"{'type': 'Point', 'coordinates': [-73.935763, ...",NaN,NaN,NaN,...,NaN,NaN,2853431,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN,0,0
1612176,2012-07-18T00:00:00.000,9:20,MANHATTAN,10024,40.779479,-73.973573,"{'type': 'Point', 'coordinates': [-73.9735729,...",CENTRAL PARK WEST,WEST 77 STREET,NaN,...,NaN,NaN,52405,SPORT UTILITY / STATION WAGON,VAN,BUS,NaN,NaN,0,0
1612177,2012-07-12T00:00:00.000,3:10,QUEENS,11361,40.762501,-73.782522,"{'type': 'Point', 'coordinates': [-73.7825216,...",39 AVENUE,203 STREET,NaN,...,NaN,NaN,259445,PASSENGER VEHICLE,NaN,NaN,NaN,NaN,0,0

Ze względu na niewielką ilość błędnych danych o sumie zabitych lub rannych usuwam te dane.

In [83]:
print(f'Ilośc wierszy przed usunięciem: {len(data)}')
data = data.drop(data.loc[data['NUMBER OF PERSONS INJURED'] != data['CHECK_INJURED'] ].index)
data = data.drop(data.loc[data['NUMBER OF PERSONS KILLED'] != data['CHECK_KILLED'] ].index)
print(f'Ilośc wierszy po usunięciu: {len(data)}')
data = data.drop(columns=['CHECK_INJURED', 'CHECK_KILLED'])

Ilośc wierszy przed usunięciem: 1612178
Ilośc wierszy po usunięciu: 1611775

Sprawdzenie czy kolumna COLLISION_ID zawiera unikatowe wartośc

In [84]:
data['COLLISION_ID'].is_unique

False

kolumna COLLISION_ID zawiera duplikaty, dlatego sprawdzam które rekordy zawierają duplikaty

In [85]:
data['tmp'] = 1
check_collision_id = data.pivot_table(index='COLLISION_ID', values='tmp', aggfunc='count').sort_values(by='tmp', ascending=False)
duplicate_collision_id = check_collision_id.loc[check_collision_id['tmp'] > 1]

Index([4248692, 4248667,      58, 4248576, 4248564, 4248266, 4248214, 4248139,
       4248126, 4248032,
       ...
       3198857, 3198678, 3198590, 3198589, 3197916, 3197491, 3195224, 3194231,
       4249078,      40],
      dtype='int64', name='COLLISION_ID', length=394158)

sprawdzam czy zdublowane collision_id zawierają dokładnie te same informacje

In [86]:
bad_groups = data.groupby("COLLISION_ID").nunique().gt(1).any(axis=1).sort_values(ascending=False)
print(f'jest {len(bad_groups[bad_groups])} wierszy które zawierają rózne dane w ramach tego samogo collision_id')
print(f'jest {len(bad_groups[~bad_groups])} wierszy które zawierają takie same dane w ramach tego samogo collision_id')

jest 0 wierszy które zawierają rózne dane w ramach tego samogo collision_id
jest 1217617 wierszy które zawierają takie same dane w ramach tego samogo collision_id

w związku z tym, że dane w ramach collision id zawierają dokłądnie te same dane usuwam zdublowane rekordy

In [87]:
print(f'ilośc wierszy przed usunięciem duplikatów: {len(data)}')
data = data.drop_duplicates()
print(f'ilośc wierszy po usunięciu duplikatów: {len(data)}')

ilośc wierszy przed usunięciem duplikatów: 1611775
ilośc wierszy po usunięciu duplikatów: 1217617