In [75]:
import pandas as pd

# Pobranie danych

In [76]:
data = pd.read_csv('data/dane_projektowe_ny_collisions.csv', low_memory=False)

# Eksploracja danych wraz z określeniem dalszych kroków czyszczenia danych

In [77]:
data.describe()

,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,COLLISION_ID
count,1.415893e+06,1.415893e+06,1.612161e+06,1.612145e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06,1.612178e+06
mean,4.068864e+01,-7.386657e+01,2.631363e-01,1.185998e-03,5.060483e-02,6.302034e-04,2.098590e-02,9.242156e-05,1.916854e-01,4.633483e-04,2.765946e+06
std,1.200403e+00,2.438640e+00,6.584832e-01,3.644859e-02,2.316972e-01,2.577872e-02,1.445222e-01,9.677481e-03,6.206497e-01,2.334547e-02,1.506373e+06
min,0.000000e+00,-2.012371e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+01
25%,4.066882e+01,-7.397746e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.014464e+06
50%,4.072258e+01,-7.393002e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.422826e+06
75%,4.076789e+01,-7.386727e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.854210e+06
max,4.231832e+01,0.000000e+00,3.100000e+01,8.000000e+00,2.700000e+01,6.000000e+00,4.000000e+00,2.000000e+00,3.100000e+01,5.000000e+00,4.249104e+06

In [78]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1612178 entries, 0 to 1612177
Data columns (total 29 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   ACCIDENT DATE                  1612178 non-null  str
 1   ACCIDENT TIME                  1612178 non-null  str
 2   BOROUGH                        1127553 non-null  str
 3   ZIP CODE                       1127376 non-null  str
 4   LATITUDE                       1415893 non-null  float64
 5   LONGITUDE                      1415893 non-null  float64
 6   LOCATION                       1415893 non-null  str
 7   ON STREET NAME                 1298002 non-null  str
 8   CROSS STREET NAME              1079193 non-null  str
 9   OFF STREET NAME                219732 non-null   str
 10  NUMBER OF PERSONS INJURED      1612161 non-null  float64
 11  NUMBER OF PERSONS KILLED       1612145 non-null  float64
 12  NUMBER OF PEDESTRIANS INJURED  1612178 non-null  int64
 13  NUMBER OF PEDESTRIANS KILLED   1612178 non-null  int64
 14  NUMBER OF CYCLIST INJURED      1612178 non-null  int64
 15  NUMBER OF CYCLIST KILLED       1612178 non-null  int64
 16  NUMBER OF MOTORIST INJURED     1612178 non-null  int64
 17  NUMBER OF MOTORIST KILLED      1612178 non-null  int64
 18  CONTRIBUTING FACTOR VEHICLE 1  1607854 non-null  str
 19  CONTRIBUTING FACTOR VEHICLE 2  1396127 non-null  str
 20  CONTRIBUTING FACTOR VEHICLE 3  104254 non-null   str
 21  CONTRIBUTING FACTOR VEHICLE 4  21789 non-null    str
 22  CONTRIBUTING FACTOR VEHICLE 5  5622 non-null     str
 23  COLLISION_ID                   1612178 non-null  int64
 24  VEHICLE TYPE CODE 1            1606597 non-null  str
 25  VEHICLE TYPE CODE 2            1346858 non-null  str
 26  VEHICLE TYPE CODE 3            128742 non-null   str
 27  VEHICLE TYPE CODE 4            46009 non-null    str
 28  VEHICLE TYPE CODE 5            10150 non-null    str
dtypes: float64(4), int64(7), str(18)
memory usage: 667.6 MB

In [79]:
data.head(1000).loc[data['NUMBER OF PERSONS KILLED'] > 0]

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
7,2019-08-11T00:00:00.000,22:23,NaN,NaN,40.858210,-73.91679,"{'type': 'Point', 'coordinates': [-73.91679, 4...",MAJOR DEEGAN EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4187134,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
467,2019-08-02T00:00:00.000,10:25,QUEENS,11378,40.725918,-73.89535,"{'type': 'Point', 'coordinates': [-73.89535, 4...",GRAND AVENUE,69 STREET,NaN,...,NaN,NaN,NaN,NaN,4181646,Dump,NaN,NaN,NaN,NaN
540,2019-08-24T00:00:00.000,16:30,BROOKLYN,11236,40.644814,-73.90483,"{'type': 'Point', 'coordinates': [-73.90483, 4...",NaN,NaN,1037 EAST 95 STREET,...,Unspecified,NaN,NaN,NaN,4194033,Motorcycle,Pick-up Truck,NaN,NaN,NaN
708,2019-08-11T00:00:00.000,12:27,BROOKLYN,11230,40.619984,-73.96427,"{'type': 'Point', 'coordinates': [-73.96427, 4...",CONEY ISLAND AVENUE,AVENUE L,NaN,...,Unspecified,Unspecified,NaN,NaN,4188033,Sedan,Bike,Station Wagon/Sport Utility Vehicle,NaN,NaN
911,2019-08-29T00:00:00.000,2:35,NaN,NaN,40.834890,-73.86630,"{'type': 'Point', 'coordinates': [-73.8663, 40...",CROSS BRONX EXPY,NaN,NaN,...,NaN,NaN,NaN,NaN,4196472,Dump,NaN,NaN,NaN,NaN

Sprawdzenie czy kolumny liczbowe o zabitych i rannych nie zawierają ujemnych wartości

In [80]:
list_of_numeric_columns_injured_or_killed=['NUMBER OF PERSONS INJURED', 'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED', 'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED', 'NUMBER OF MOTORIST KILLED']

In [81]:
for i in list_of_numeric_columns_injured_or_killed:
    min_value = data[i].min()
    if min_value < 0:
        print(f'kolumna {i} zawiera ujemne wartości, prawdopodobnie błędne dane')
    else:
        print(f'kolumna {i} zawiera zerowe lub dodatnie wartości')

kolumna NUMBER OF PERSONS INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PERSONS KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PEDESTRIANS INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF PEDESTRIANS KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF CYCLIST INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF CYCLIST KILLED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF MOTORIST INJURED zawiera zerowe lub dodatnie wartości
kolumna NUMBER OF MOTORIST KILLED zawiera zerowe lub dodatnie wartości

Sprawdzenie czy suma kolumn o zabitych i rannych jest zgodna z kolumnami z sumami

In [82]:
dict_killed_injured = {'NUMBER OF PERSONS INJURED': [['NUMBER OF PEDESTRIANS INJURED', 'NUMBER OF CYCLIST INJURED', 'NUMBER OF MOTORIST INJURED' ], 'CHECK_INJURED'], 'NUMBER OF PERSONS KILLED': [['NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST KILLED'], 'CHECK_KILLED']}
data[['CHECK_KILLED', 'CHECK_INJURED']] = 0
for i, j in dict_killed_injured.items():
    for k in j[0]:
        data[j[1]] = data[j[1]] + data[k]
data

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5,CHECK_KILLED,CHECK_INJURED
0,2019-08-05T00:00:00.000,16:30,QUEENS,11434,40.676052,-73.790184,"{'type': 'Point', 'coordinates': [-73.790184, ...",NaN,NaN,150-08 123 AVENUE,...,NaN,NaN,4184637,Sedan,Pick-up Truck,NaN,NaN,NaN,0,0
1,2019-08-27T00:00:00.000,16:02,BROOKLYN,11225,40.657780,-73.951096,"{'type': 'Point', 'coordinates': [-73.951096, ...",NaN,NaN,288 HAWTHORNE STREET,...,NaN,NaN,4195773,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,0,0
2,2019-08-15T00:00:00.000,17:57,MANHATTAN,10002,40.718143,-73.993835,"{'type': 'Point', 'coordinates': [-73.993835, ...",CHRYSTIE STREET,GRAND STREET,NaN,...,NaN,NaN,4202457,Sedan,NaN,NaN,NaN,NaN,0,1
3,2019-08-30T00:00:00.000,21:53,BRONX,10460,40.840534,-73.866610,"{'type': 'Point', 'coordinates': [-73.86661, 4...",NaN,NaN,1837 EAST TREMONT AVENUE,...,NaN,NaN,4198749,Taxi,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN,0,0
4,2019-08-06T00:00:00.000,9:45,MANHATTAN,10016,40.745440,-73.975400,"{'type': 'Point', 'coordinates': [-73.9754, 40...",EAST 35 STREET,2 AVENUE,NaN,...,NaN,NaN,4183798,Station Wagon/Sport Utility Vehicle,Bike,NaN,NaN,NaN,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612173,2012-07-21T00:00:00.000,22:46,BROOKLYN,11226,40.651741,-73.965241,"{'type': 'Point', 'coordinates': [-73.9652409,...",PARADE PLACE,CROOKE AVENUE,NaN,...,NaN,NaN,147595,SPORT UTILITY / STATION WAGON,UNKNOWN,NaN,NaN,NaN,0,0
1612174,2012-07-09T00:00:00.000,16:45,NaN,NaN,NaN,NaN,NaN,EDWARD L GRANT HIGHWAY,WEST 169 STREET,NaN,...,NaN,NaN,85220,PASSENGER VEHICLE,LIVERY VEHICLE,PASSENGER VEHICLE,NaN,NaN,0,5
1612175,2012-07-09T00:00:00.000,14:35,NaN,NaN,40.791492,-73.935763,"{'type': 'Point', 'coordinates': [-73.935763, ...",NaN,NaN,NaN,...,NaN,NaN,2853431,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN,0,0
1612176,2012-07-18T00:00:00.000,9:20,MANHATTAN,10024,40.779479,-73.973573,"{'type': 'Point', 'coordinates': [-73.9735729,...",CENTRAL PARK WEST,WEST 77 STREET,NaN,...,NaN,NaN,52405,SPORT UTILITY / STATION WAGON,VAN,BUS,NaN,NaN,0,0
1612177,2012-07-12T00:00:00.000,3:10,QUEENS,11361,40.762501,-73.782522,"{'type': 'Point', 'coordinates': [-73.7825216,...",39 AVENUE,203 STREET,NaN,...,NaN,NaN,259445,PASSENGER VEHICLE,NaN,NaN,NaN,NaN,0,0

Ze względu na niewielką ilość błędnych danych o sumie zabitych lub rannych usuwam te dane.

In [83]:
print(f'Ilośc wierszy przed usunięciem: {len(data)}')
data = data.drop(data.loc[data['NUMBER OF PERSONS INJURED'] != data['CHECK_INJURED'] ].index)
data = data.drop(data.loc[data['NUMBER OF PERSONS KILLED'] != data['CHECK_KILLED'] ].index)
print(f'Ilośc wierszy po usunięciu: {len(data)}')
data = data.drop(columns=['CHECK_INJURED', 'CHECK_KILLED'])

Ilośc wierszy przed usunięciem: 1612178
Ilośc wierszy po usunięciu: 1611775

Sprawdzenie czy kolumna COLLISION_ID zawiera unikatowe wartośc

In [84]:
data['COLLISION_ID'].is_unique

False

kolumna COLLISION_ID zawiera duplikaty, dlatego sprawdzam które rekordy zawierają duplikaty

In [85]:
data['tmp'] = 1
check_collision_id = data.pivot_table(index='COLLISION_ID', values='tmp', aggfunc='count').sort_values(by='tmp', ascending=False)
duplicate_collision_id = check_collision_id.loc[check_collision_id['tmp'] > 1]
data = data.drop(columns=['tmp'])
print(f'znaleziono zduplikowane collision_id w liczbie: {len(duplicate_collision_id)}')

Index([4248692, 4248667,      58, 4248576, 4248564, 4248266, 4248214, 4248139,
       4248126, 4248032,
       ...
       3198857, 3198678, 3198590, 3198589, 3197916, 3197491, 3195224, 3194231,
       4249078,      40],
      dtype='int64', name='COLLISION_ID', length=394158)

sprawdzam czy zdublowane collision_id zawierają dokładnie te same informacje

In [86]:
bad_groups = data.groupby("COLLISION_ID").nunique().gt(1).any(axis=1).sort_values(ascending=False)
print(f'jest {len(bad_groups[bad_groups])} wierszy które zawierają rózne dane w ramach tego samogo collision_id')
print(f'jest {len(bad_groups[~bad_groups])} wierszy które zawierają takie same dane w ramach tego samogo collision_id')

jest 0 wierszy które zawierają rózne dane w ramach tego samogo collision_id
jest 1217617 wierszy które zawierają takie same dane w ramach tego samogo collision_id

w związku z tym, że dane w ramach collision id zawierają dokłądnie te same dane usuwam zdublowane rekordy

In [87]:
print(f'ilośc wierszy przed usunięciem duplikatów: {len(data)}')
data = data.drop_duplicates()
print(f'ilośc wierszy po usunięciu duplikatów: {len(data)}')

ilośc wierszy przed usunięciem duplikatów: 1611775
ilośc wierszy po usunięciu duplikatów: 1217617

W związku z bardzo zła jakością danych odnbosnie typów samochodów, dodaje ręcznie przygotowany słownik który poprawia błędy w danych

In [91]:
DICT_TO_REPLACE = {	 'SEDAN':[ '2 DR SEDAN', '4 DR SEDAN', 'SE', 'SEA',],	 'AMBULANCE':[ 'AM', 'AMABU', 'AMB', 'AMBU', 'AMBUL',],	 'BICYCLE':[ 'BICYC', 'BIKE', 'BK',],	 'BOX TRUCK':[ 'BOX', 'BOX T', 'BOXTR',],	 'CONCRETE MIXER':[ 'CONCR',],	 'CONVERTIBLE':[ 'CONV', 'CONVE',],	 'DELIVERY':[ 'DEL', 'DELIV', 'DELV', 'DELVI',],	 'DUMP':[ 'DUMPS', 'DUMPT',],	 'FIRE TRUCK':[ 'FD NY', 'FDNY', 'FIRE', 'FIRET',],	 'FLAT BED':[ 'FLATB',],	 'GARBAGE OR REFUSE':[ 'GARBA',],	 'LARGE COM VEH(6 OR MORE TIRES)':[ 'LADDE',],	 'LIVERY VEHICLE':[ 'LIVER',],	 'MOPED':[ 'MOPD',],	 'PASSENGER VEHICLE':[ 'PASSA', 'PASSE',],	 'PICK-UP TRUCK':[ 'PICK', 'PICK-', 'PICKU',],	 'REFRIGERATED VAN':[ 'REFRI',],	 'SCHOOL BUS':[ 'SCHOO',],	 'SCOOTER':[ 'SCOO', 'SCOOT',],	 'TANKER':[ 'TANK', 'TANKE',],	 'TOW TRUCK / WRECKER':[ 'TOW', 'TOW T', 'TOW TRUCK', 'TOW-T', 'TOWTR',],	 'VAN':[ 'VAB', 'VAN (', 'VAN CAMPER', 'VAN T', 'VAN/T', 'VANETTE',]	}
for i, j in DICT_TO_REPLACE.items():
    for z in range(1,6):
        data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i

C:\Users\piotr\AppData\Local\Temp\ipykernel_40464\597417782.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data[f'VEHICLE TYPE CODE {z}'].loc[data[f'VEHICLE TYPE CODE {z}'].isin(j)] = i

Ujendolicam i poprawiam wartości kategoryczne typów samochodów

In [93]:
data['VEHICLE TYPE CODE 1'] = data['VEHICLE TYPE CODE 1'].str.upper()
data['VEHICLE TYPE CODE 2'] = data['VEHICLE TYPE CODE 2'].str.upper()
data['VEHICLE TYPE CODE 3'] = data['VEHICLE TYPE CODE 3'].str.upper()
data['VEHICLE TYPE CODE 4'] = data['VEHICLE TYPE CODE 4'].str.upper()
data['VEHICLE TYPE CODE 5'] = data['VEHICLE TYPE CODE 5'].str.upper()

In [94]:
list_to_change_unkonw =[ '00',
 '11 PA',
 '16M',
 '18 WH',
 '2 DOO',
 '2 HOR',
 '2TON',
 '3-WHE',
 '3DC-',
 '4DR',
 '52? T',
 '72000',
 '994',
 'ALUMI',
 'ANBUL',
 'APURP',
 'ART M',
 'ASPHA',
 'AXO',
 'B5-44',
 'BED',
 'BLOCK',
 'BOB C',
 'BOOML',
 'BROOM',
 'BROWN',
 'BUMP',
 'C0MME',
 'CAMPE',
 'CAR C',
 'CARRI',
 'CASE',
 'CAT',
 'CAT 3',
 'CAT 4',
 'CAT32',
 'CB534',
 'CHEVR',
 'CHURC',
 'COMPA',
 'CONTA',
 'CRWZK',
 'D',
 'D1',
 'DELV.',
 'DEPAR',
 'DETAC',
 'DIG-I',
 'DIRTB',
 'DOT #',
 'DSNY',
 'E',
 'E PAS',
 'E-350',
 'E-SKA',
 'E250',
 'E3',
 'E350',
 'EB',
 'EMS',
 'EMT',
 'EXPRE',
 'FARM',
 'FD LA',
 'FLTRL',
 'FORTL',
 'FRE T',
 'FRIEG',
 'G OMR',
 'G PAS',
 'G SEM',
 'G TOW',
 'GARAB',
 'GAS S',
 'GAS T',
 'GLBEN',
 'GMC V',
 'GOLF',
 'GOV V',
 'GOV\'T',
 'HARVE',
 'HI-LO',
 'HIGHL',
 'HOE-L',
 'HOOK',
 'HOTDO',
 'HOUSE',
 'JCB40',
 'JLG B',
 'JLG L',
 'JOHND',
 'LAUND',
 'LG',
 'LL',
 'MAN L',
 'MECHA',
 'MINIV',
 'MO-PE',
 'MOPEN',
 'MOPET',
 'MV',
 'N/A',
 'NA',
 'NEW Y',
 'NV CA',
 'NV150',
 'NYC',
 'NYFD',
 'OFF R',
 'OLM',
 'OML/',
 'OP',
 'PALLE',
 'PASS',
 'PAVIN',
 'PCH',
 'PEDIC',
 'PISH',
 'PLOW',
 'POST',
 'PUMPE',
 'PUSH',
 'RAM',
 'RAZOR',
 'RD/S',
 'RED,',
 'RGS',
 'ROADS',
 'S/SP',
 'SAFET',
 'SBN',
 'SCAFF',
 'SCAVA',
 'SCHOOL BUS',
 'SELF-',
 'SHCOO',
 'SKID',
 'SMALL',
 'SPEC-',
 'SUDAN',
 'SWT',
 'T650',
 'TAN P',
 'TCR',
 'TKP',
 'TL TR',
 'TLR',
 'TOUR',
 'TOWER',
 'TOWIN',
 'TRA/R',
 'TRAIN',
 'TRASH',
 'TRIAL',
 'TRIM',
 'TRT',
 'TUGGE',
 'U HAU',
 'U-TRU',
 'UBER',
 'UD',
 'ULITI',
 'UNK,',
 'UNNKO',
 'US MA',
 'UTLIT',
 'UTLL',
 'VAN A',
 'VAN C',
 'VAN F',
 'VAN W',
 'VAN/B',
 'VMS T',
 'WASTE',
 'WC',
 'WESCO',
 '(CEME',
 '1',
 '12 PA',
 '15 PA',
 '2 TON',
 '2015',
 '3 WHE',
 '3-DOOR',
 '35 FT',
 '3D',
 '4 RUN',
 '4D',
 '4DS',
 '4DSD',
 '985',
 'A',
 'ACCES',
 'APORT',
 'APPOR',
 'AR',
 'ARMOR',
 'ARMY',
 'ATTAC',
 'BA',
 'BACK',
 'BACKH',
 'BARRI',
 'BED T',
 'BOBCA',
 'BOOM',
 'BR',
 'BS',
 'C1',
 'C3',
 'CAB',
 'CAMP',
 'CARGO',
 'CAT 9',
 'CAT P',
 'CAT.',
 'CATE',
 'CATER',
 'CB',
 'CEMEN',
 'CHEVO',
 'CHEVY',
 'CITY',
 'CM',
 'CMIX',
 'CMS-T',
 'CO',
 'COM',
 'COM T',
 'COM.',
 'COMB',
 'COMER',
 'COMIX',
 'COMM',
 'COMME',
 'COMMM',
 'CONST',
 'COURI',
 'CRANE',
 'CUSHM',
 'DP',
 'DUNBA',
 'E - B',
 'E AMB',
 'E BIK',
 'E ONE',
 'E SCO',
 'E- BI',
 'E.M.S',
 'E/BIK',
 'E450',
 'EBIKE',
 'ECONO',
 'ELEC.',
 'ELECT',
 'EMRGN',
 'EMS A',
 'EMS B',
 'EMS H',
 'EN',
 'ENCLOSED BODY - NONREMOVABLE ENCLOSURE',
 'ENCLOSED BODY - REMOVABLE ENCLOSURE',
 'ENGIN',
 'EPO',
 'ESU T',
 'EXCAV',
 'F550',
 'FD FI',
 'FED E',
 'FEDER',
 'FEDEX',
 'FOOD',
 'FORD',
 'FORK',
 'FORK-',
 'FORKL',
 'FR',
 'FREE',
 'FREIG',
 'FRHT',
 'FRONT',
 'FR`',
 'FUEL',
 'G COM',
 'G SPC',
 'GATOR',
 'GE/SC',
 'GEICO',
 'GOKAR',
 'GOVER',
 'GR',
 'GRAIN',
 'GRAY',
 'GRUMM',
 'HAND',
 'HEAVY',
 'HELP',
 'HI TA',
 'HINO',
 'HO',
 'HOPPER',
 'HORSE',
 'HRSE',
 'HUMME',
 'HWY C',
 'ICE C',
 'ICECR',
 'INTER',
 'IP',
 'JEEP',
 'JOHN',
 'KENWO',
 'KUBOT',
 'L1',
 'LD',
 'LF',
 'LIEBH',
 'LIFT',
 'LIFT BOOM',
 'LIGHT',
 'LIMO',
 'LIMOU',
 'LIVESTOCK RACK',
 'LOADE',
 'LOG',
 'LP',
 'LTR',
 'LTRL',
 'LUNCH WAGON',
 'LW',
 'MAC T',
 'MACK',
 'MAIL',
 'MARK',
 'MARKE',
 'MB',
 'MC',
 'MCY B',
 'MD',
 'ME/BE',
 'MH',
 'MINI',
 'MINIBIKE',
 'MINICYCLE',
 'MK',
 'MOBIL',
 'MOPAD',
 'MOVIN',
 'MS',
 'MTA',
 'MTA B',
 'MTA C',
 'MTR S',
 'MULTI-WHEELED VEHICLE',
 'NAVIG',
 'NISSA',
 'NONE',
 'NS AM',
 'NYC A',
 'NYC B',
 'NYC D',
 'NYC F',
 'NYC M',
 'NYCHA',
 'NYPD',
 'NYS A',
 'OIL T',
 'OLC',
 'OML',
 'OMNI',
 'OMNIB',
 'OMR',
 'OMT',
 'OPEN BODY',
 'OTHER',
 'P/SH',
 'PALLET',
 'PARCE',
 'PAS',
 'PAYLO',
 'PC',
 'PEDICAB',
 'PK',
 'PKUP',
 'PL',
 'PM',
 'POIS',
 'POLIC',
 'POSTA',
 'POSTO',
 'POWER',
 'PRKS',
 'PSD',
 'PSH',
 'PSR',
 'PU',
 'PUMP',
 'R/V',
 'R/V C',
 'RANGE',
 'RED T',
 'REFG',
 'RENTA',
 'REP',
 'REPAI',
 'RESCU',
 'RF',
 'RMB',
 'RMP',
 'RMP V',
 'ROAD',
 'RV',
 'RYDER',
 'SANIT',
 'SANTA',
 'SANTI',
 'SCISS',
 'SELF',
 'SEMI',
 'SEMI-',
 'SGWS',
 'SKATE',
 'SKID-',
 'SMART',
 'SNOW',
 'SNOW PLOW',
 'SP',
 'SPC',
 'SPC P',
 'SPEC',
 'SPRIN',
 'SS',
 'ST',
 'ST150',
 'STAK',
 'STAKE OR RACK',
 'STATE',
 'STREE',
 'SUB',
 'SUBN',
 'SUBN/',
 'SUBUR',
 'SUV',
 'SW',
 'SWEEP',
 'TCN',
 'TRC',
 'TRK',
 'TRL',
 'TRLPM',
 'TRLR',
 'U-HAU',
 'U.S.',
 'UHAUL',
 'UHUAL',
 'UKN',
 'ULILI',
 'UNK',
 'UNKNO',
 'UNKNOWN',
 'UNKOW',
 'UPS T',
 'US PO',
 'USP M',
 'USPOS',
 'USPS',
 'USPS2',
 'UT',
 'UTIL',
 'UTILI',
 'VANG',
 'VC',
 'VERIZ',
 'VESPA',
 'VT',
 'WAGON',
 'WD',
 'WELL DRILLER',
 'WHBL',
 'WHEEL',
 'WHITE',
 'WINEB',
 'WINNE',
 'WORK',
 'YELLO',
 '\x7fOMM',
 'Ï¿½MBU',
                          'BUCKE',
 'BUDGE',
 'BULK AGRICULTURE',
 'BULLD',
 'CONT',
 'DEMA-',
 'DEPT',
 'DIESE',
 'DIRT',
 'DOT R',
 'DOT T',
 'FD TR',
 'FLAT',
 'FLAT/',
 'MOTER',
 'MOTOR',
 'MOTOR HOME',
 'MOTORBIKE',
 'MOTORIZED HOME',
 'TE',
 'TF',
 'TN',
 'TR',
 'TRAC',
 'TRAC.',
 'TRACK',
 'TRACT',
 'TRAFF',
 'TRAM',
 'TRANS',
 'VOL',
]
data['VEHICLE TYPE CODE 1'].loc[data['VEHICLE TYPE CODE 1'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 2'].loc[data['VEHICLE TYPE CODE 2'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 3'].loc[data['VEHICLE TYPE CODE 3'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 4'].loc[data['VEHICLE TYPE CODE 4'].isin(list_to_change_unkonw)] = 'UNKNOWN'
data['VEHICLE TYPE CODE 5'].loc[data['VEHICLE TYPE CODE 5'].isin(list_to_change_unkonw)] = 'UNKNOWN'

C:\Users\piotr\AppData\Local\Temp\ipykernel_40464\2049670938.py:520: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data['VEHICLE TYPE CODE 1'].loc[data['VEHICLE TYPE CODE 1'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_40464\2049670938.py:521: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data['VEHICLE TYPE CODE 2'].loc[data['VEHICLE TYPE CODE 2'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_40464\2049670938.py:522: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data['VEHICLE TYPE CODE 3'].loc[data['VEHICLE TYPE CODE 3'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_40464\2049670938.py:523: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data['VEHICLE TYPE CODE 4'].loc[data['VEHICLE TYPE CODE 4'].isin(list_to_change_unkonw)] = 'UNKNOWN'
C:\Users\piotr\AppData\Local\Temp\ipykernel_40464\2049670938.py:524: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  data['VEHICLE TYPE CODE 5'].loc[data['VEHICLE TYPE CODE 5'].isin(list_to_change_unkonw)] = 'UNKNOWN'

Poprawiam powody wypadków

In [97]:
data['CONTRIBUTING FACTOR VEHICLE 1'] = data['CONTRIBUTING FACTOR VEHICLE 1'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 2'] = data['CONTRIBUTING FACTOR VEHICLE 2'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 3'] = data['CONTRIBUTING FACTOR VEHICLE 3'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 4'] = data['CONTRIBUTING FACTOR VEHICLE 4'].str.upper()
data['CONTRIBUTING FACTOR VEHICLE 5'] = data['CONTRIBUTING FACTOR VEHICLE 5'].str.upper()
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1']=='80') | (data['CONTRIBUTING FACTOR VEHICLE 1']=='1'), 'CONTRIBUTING FACTOR VEHICLE 1'] = 'UNSPECIFIED'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1']=='ILLNES') , 'CONTRIBUTING FACTOR VEHICLE 1'] = 'ILLNESS'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1']=='REACTION TO OTHER UNINVOLVED VEHICLE') , 'CONTRIBUTING FACTOR VEHICLE 1'] = 'REACTION TO UNINVOLVED VEHICLE'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 1'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 1'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2']=='80') | (data['CONTRIBUTING FACTOR VEHICLE 2']=='1'), 'CONTRIBUTING FACTOR VEHICLE 2'] = 'UNSPECIFIED'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 2'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2']=='ILLNES') , 'CONTRIBUTING FACTOR VEHICLE 2'] = 'ILLNESS'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 2']=='REACTION TO OTHER UNINVOLVED VEHICLE') , 'CONTRIBUTING FACTOR VEHICLE 2'] = 'REACTION TO UNINVOLVED VEHICLE'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3']=='80') | (data['CONTRIBUTING FACTOR VEHICLE 3']=='1'), 'CONTRIBUTING FACTOR VEHICLE 3'] = 'UNSPECIFIED'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 3'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3']=='ILLNES') , 'CONTRIBUTING FACTOR VEHICLE 3'] = 'ILLNESS'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 3']=='REACTION TO OTHER UNINVOLVED VEHICLE') , 'CONTRIBUTING FACTOR VEHICLE 3'] = 'REACTION TO UNINVOLVED VEHICLE'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 4'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 4'] = 'EMPTY'
data.loc[(data['CONTRIBUTING FACTOR VEHICLE 5'].isna()) , 'CONTRIBUTING FACTOR VEHICLE 5'] = 'EMPTY'

In [98]:
data['CONTRIBUTING FACTOR VEHICLE 1'].drop_duplicates().sort_values()

6264                                 ACCELERATOR DEFECTIVE
17                            AGGRESSIVE DRIVING/ROAD RAGE
131                                    ALCOHOL INVOLVEMENT
1740                                        ANIMALS ACTION
32                                        BACKING UNSAFELY
36                                        BRAKES DEFECTIVE
2011                                CELL PHONE (HAND-HELD)
2902                               CELL PHONE (HANDS-FREE)
2                           DRIVER INATTENTION/DISTRACTION
152                                    DRIVER INEXPERIENCE
19                              DRIVERLESS/RUNAWAY VEHICLE
43                                         DRUGS (ILLEGAL)
36761                                   EATING OR DRINKING
450                                                  EMPTY
100                                  FAILURE TO KEEP RIGHT
25                           FAILURE TO YIELD RIGHT-OF-WAY
819                                        FATIGUED/DROWSY
941                                            FELL ASLEEP
10                                   FOLLOWING TOO CLOSELY
960                                                  GLARE
68624                                 HEADLIGHTS DEFECTIVE
928                                                ILLNESS
55                        LANE MARKING IMPROPER/INADEQUATE
4997                            LISTENING/USING HEADPHONES
493                                     LOST CONSCIOUSNESS
101                                     OBSTRUCTION/DEBRIS
8863                               OTHER ELECTRONIC DEVICE
3101                                OTHER LIGHTING DEFECTS
18                                         OTHER VEHICULAR
107                                OUTSIDE CAR DISTRACTION
525                                      OVERSIZED VEHICLE
516                                  PASSENGER DISTRACTION
12                          PASSING OR LANE USAGE IMPROPER
0                                      PASSING TOO CLOSELY
51                                      PAVEMENT DEFECTIVE
182                                      PAVEMENT SLIPPERY
225      PEDESTRIAN/BICYCLIST/OTHER PEDESTRIAN ERROR/CO...
1559                                   PHYSICAL DISABILITY
1735                               PRESCRIPTION MEDICATION
8                           REACTION TO UNINVOLVED VEHICLE
40608                         SHOULDERS DEFECTIVE/IMPROPER
952                                       STEERING FAILURE
44416                                              TEXTING
20659                                       TINTED WINDOWS
90                                 TIRE FAILURE/INADEQUATE
7227                                   TOW HITCH DEFECTIVE
6073           TRAFFIC CONTROL DEVICE IMPROPER/NON-WORKING
53                             TRAFFIC CONTROL DISREGARDED
22                                      TURNING IMPROPERLY
16                                    UNSAFE LANE CHANGING
7                                             UNSAFE SPEED
3                                              UNSPECIFIED
412                       USING ON BOARD NAVIGATION DEVICE
7581                                     VEHICLE VANDALISM
14                                 VIEW OBSTRUCTED/LIMITED
26539                                WINDSHIELD INADEQUATE
Name: CONTRIBUTING FACTOR VEHICLE 1, dtype: str

sprawdzenie dzielnicy i kodu pocztowego oraz proba ich uzupelnienia na podstawie danych

In [100]:
data['brak_wspolrzednych']=False
empty_location = data.loc[((data['LONGITUDE'].isna()) | (data['LATITUDE'].isna())) | ((data['LONGITUDE'] == 0.0) | (data['LATITUDE'] == 0.0))]
data.loc[empty_location.index, 'brak_wspolrzednych'] = True
data['brak_dzielnicy'] = False
data['brak_kodu'] = False
empty_BOROUGH = data.loc[data['BOROUGH'].isna()]
empty_zip_code = data.loc[data['ZIP CODE'].isna()]
data.loc[empty_BOROUGH.index, 'brak_dzielnicy'] = True
data.loc[empty_BOROUGH.index, 'brak_kodu'] = True
uniq_location_and_borough = data[['BOROUGH', 'ZIP CODE', 'LATITUDE', 'LONGITUDE']].loc[
 data['brak_wspolrzednych'] == False].drop_duplicates()
uniq_location_and_borough
uniq_location_and_borough_with_all_data = uniq_location_and_borough.loc[uniq_location_and_borough['BOROUGH'].notna()]
uniq_location_and_borough_without_all_data = uniq_location_and_borough.loc[uniq_location_and_borough['BOROUGH'].isna()]
uniq_location_and_borough_with_all_data['row_number'] = uniq_location_and_borough_with_all_data.groupby(
 ['LATITUDE', 'LONGITUDE']).cumcount() + 1
pivot_uniq = uniq_location_and_borough_with_all_data.pivot_table(index=['LATITUDE', 'LONGITUDE'], values='row_number',
                                                                 aggfunc='max')
pivot_uniq_only_1_row_number = pivot_uniq.loc[pivot_uniq['row_number'] == 1]
pivot_uniq_only_1_row_number = pivot_uniq_only_1_row_number.rename(columns={'row_number': 'wartosc_tymczasowa'})
uniq_location_and_borough_with_all_data_add_good_data = uniq_location_and_borough_with_all_data.merge(
 pivot_uniq_only_1_row_number, how='left', on=['LATITUDE', 'LONGITUDE'])
uniq_location_and_borough_with_all_data_to_merge = uniq_location_and_borough_with_all_data_add_good_data.loc[
 uniq_location_and_borough_with_all_data_add_good_data['wartosc_tymczasowa'] == 1]
uniq_location_and_borough_with_all_data_to_merge
data = data.merge(uniq_location_and_borough_with_all_data_to_merge, how='left', on=['LATITUDE', 'LONGITUDE'],
                  suffixes=('', '_completed'))

data['uzupelniona_dzielnica'] = False
data['uzupelniony_kod_pocztowy'] = False
data.loc[(data['BOROUGH_completed'].notna() & (data['BOROUGH'].isna())), 'uzupelniona_dzielnica'] = True

data.loc[(data['ZIP CODE_completed'].notna() & (data['ZIP CODE'].isna())), 'uzupelniony_kod_pocztowy'] = True
data.loc[(data['uzupelniona_dzielnica'] == True) & (data['brak_dzielnicy'] == True), 'BOROUGH'] = data[
 'BOROUGH_completed']
data.loc[(data['uzupelniony_kod_pocztowy'] == True) & (data['brak_kodu'] == True), 'ZIP CODE'] = data[
 'ZIP CODE_completed']
# poprawa warrtosci katerogtycznych CONTRIBUTING FACTOR VEHICLE

Sprawdzam, czy można usunąc kolumną location

In [103]:
location_test = data[['LATITUDE', 'LONGITUDE', 'LOCATION']]
location_test['part_LONG'] = location_test['LOCATION'].str.split(",").str[1].str.replace("'coordinates': [", '',
                                                                                         regex=False)
location_test['part_LAT'] = location_test['LOCATION'].str.split(",").str[2].str.replace(']}', '', regex=False)
location_test['part_LONG'] = location_test['part_LONG'].astype(float)
location_test['part_LAT'] = location_test['part_LAT'].astype(float)
test_lat = location_test.loc[location_test['LATITUDE'] != location_test['part_LAT']].dropna(subset=['LOCATION'])
test_long = location_test.loc[location_test['LONGITUDE'] != location_test['part_LONG']].dropna(subset=['LOCATION'])
data = data.drop(columns=['LOCATION'])

usuwwanie zbednych kolumn tymczasowych

In [105]:
data.loc[(data['uzupelniona_dzielnica'] ==True) & (data['brak_dzielnicy'] == True), 'brak_dzielnicy'] = False
data.loc[(data['uzupelniony_kod_pocztowy'] ==True) & (data['brak_kodu'] == True), 'brak_kodu'] = False

In [110]:
data = data.drop(columns=['uzupelniony_kod_pocztowy', 'uzupelniona_dzielnica', 'row_number', 'wartosc_tymczasowa', 'BOROUGH_completed', 'ZIP CODE_completed', 'tmp'])

KeyError: "['uzupelniony_kod_pocztowy', 'uzupelniona_dzielnica', 'row_number', 'wartosc_tymczasowa', 'BOROUGH_completed', 'ZIP CODE_completed', 'tmp'] not found in axis"

In [111]:
data

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,...,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5,brak_dzielnicy,brak_kodu,brak_wspolrzednych
0,2019-08-05T00:00:00.000,16:30,QUEENS,11434,40.676052,-73.790184,NaN,NaN,150-08 123 AVENUE,0.0,...,EMPTY,4184637,SEDAN,PICK-UP TRUCK,NaN,NaN,NaN,False,False,False
1,2019-08-27T00:00:00.000,16:02,BROOKLYN,11225,40.657780,-73.951096,NaN,NaN,288 HAWTHORNE STREET,0.0,...,EMPTY,4195773,STATION WAGON/SPORT UTILITY VEHICLE,STATION WAGON/SPORT UTILITY VEHICLE,NaN,NaN,NaN,False,False,False
2,2019-08-15T00:00:00.000,17:57,MANHATTAN,10002,40.718143,-73.993835,CHRYSTIE STREET,GRAND STREET,NaN,1.0,...,EMPTY,4202457,SEDAN,NaN,NaN,NaN,NaN,False,False,False
3,2019-08-30T00:00:00.000,21:53,BRONX,10460,40.840534,-73.866610,NaN,NaN,1837 EAST TREMONT AVENUE,0.0,...,EMPTY,4198749,TAXI,STATION WAGON/SPORT UTILITY VEHICLE,NaN,NaN,NaN,False,False,False
4,2019-08-06T00:00:00.000,9:45,MANHATTAN,10016,40.745440,-73.975400,EAST 35 STREET,2 AVENUE,NaN,1.0,...,EMPTY,4183798,STATION WAGON/SPORT UTILITY VEHICLE,BIKE,NaN,NaN,NaN,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1217612,2012-07-17T00:00:00.000,13:00,QUEENS,11419,40.687951,-73.825010,LEFFERTS BOULEVARD,103 AVENUE,NaN,0.0,...,EMPTY,228073,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN,False,False,False
1217613,2012-07-19T00:00:00.000,21:00,QUEENS,11385,40.707471,-73.910063,GREENE AVENUE,WOODWARD AVENUE,NaN,0.0,...,EMPTY,213366,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN,False,False,False
1217614,2012-07-03T00:00:00.000,9:40,NaN,NaN,40.670300,-73.997595,NaN,NaN,NaN,0.0,...,EMPTY,2964854,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,True,True,False
1217615,2012-07-11T00:00:00.000,15:42,BROOKLYN,11210,40.614136,-73.948346,AVENUE O,EAST 26 STREET,NaN,0.0,...,EMPTY,147655,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN,False,False,False
1217616,2012-07-06T00:00:00.000,6:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,EMPTY,2888479,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,NaN,NaN,NaN,True,True,True

 usuniecie odstajacych danych geograficznych

In [136]:
data = data.drop(data.loc[data['LATITUDE']<40.0].index)
data = data.drop(data.loc[(data['LONGITUDE']<-73.0) & (data['LATITUDE']>41)].index)

usueniecie zbydnych bialych znakw

In [151]:
data["OFF STREET NAME"] = data["OFF STREET NAME"].str.replace(r"\s+", " ", regex=True).str.strip()
data["ON STREET NAME"] = data["ON STREET NAME"].str.replace(r"\s+", " ", regex=True).str.strip()
data["ON STREET NAME"] = data["ON STREET NAME"].str.replace(r"\s+", " ", regex=True).str.strip()

zapis do pliku przetworzonych danych

In [137]:
data.to_csv('./data/dane_przetworzone.csv', index=False, encoding='utf-8')